const Currencies = [
  {
    value: "AUD",
    name: "Australian Dollar",
    symbol: "A$",
    decimal_digits: 2,
    countries: ["Australia"],
  },
  {
    value: "BRL",
    name: "Brazilian Real",
    symbol: "R$",
    decimal_digits: 2,
    countries: ["Brazil"],
  },
  {
    value: "GBP",
    name: "British Pound",
    symbol: "£",
    decimal_digits: 2,
    countries: ["United Kingdom"],
  },
  {
    value: "CAD",
    name: "Canadian Dollar",
    symbol: "C$",
    decimal_digits: 2,
    countries: ["Canada"],
  },
  {
    value: "CNY",
    name: "Chinese Yuan",
    symbol: "¥",
    decimal_digits: 2,
    countries: ["China"],
  },
  {
    value: "CZK",
    name: "Czech Koruna",
    symbol: "Kč",
    decimal_digits: 2,
    countries: ["Czech Republic"],
  },
  {
    value: "DKK",
    name: "Danish Krone",
    symbol: "kr",
    decimal_digits: 2,
    countries: ["Denmark"],
  },
  {
    value: "EUR",
    name: "Euro",
    symbol: "€",
    decimal_digits: 2,
    countries: ["Germany", "France", "Italy", "Spain", "Netherlands"],
  },
  {
    value: "HKD",
    name: "Hong Kong Dollar",
    symbol: "HK$",
    decimal_digits: 2,
    countries: ["Hong Kong"],
  },
  {
    value: "INR",
    name: "Indian Rupee",
    symbol: "₹",
    decimal_digits: 2,
    countries: ["India"],
  },
  {
    value: "IDR",
    name: "Indonesian Rupiah",
    symbol: "Rp",
    decimal_digits: 0,
    countries: ["Indonesia"],
  },
  {
    value: "ILS",
    name: "Israeli Shekel",
    symbol: "₪",
    decimal_digits: 2,
    countries: ["Israel"],
  },
  {
    value: "JPY",
    name: "Japanese Yen",
    symbol: "¥",
    decimal_digits: 0,
    countries: ["Japan"],
  },
  {
    value: "MYR",
    name: "Malaysian Ringgit",
    symbol: "RM",
    decimal_digits: 2,
    countries: ["Malaysia"],
  },
  {
    value: "MXN",
    name: "Mexican Peso",
    symbol: "$",
    decimal_digits: 2,
    countries: ["Mexico"],
  },
  {
    value: "NZD",
    name: "New Zealand Dollar",
    symbol: "NZ$",
    decimal_digits: 2,
    countries: ["New Zealand"],
  },
  {
    value: "NOK",
    name: "Norwegian Krone",
    symbol: "kr",
    decimal_digits: 2,
    countries: ["Norway"],
  },
  {
    value: "PHP",
    name: "Philippine Peso",
    symbol: "₱",
    decimal_digits: 2,
    countries: ["Philippines"],
  },
  {
    value: "PLN",
    name: "Polish Zloty",
    symbol: "zł",
    decimal_digits: 2,
    countries: ["Poland"],
  },
  {
    value: "RUB",
    name: "Russian Ruble",
    symbol: "₽",
    decimal_digits: 2,
    countries: ["Russia"],
  },
  {
    value: "SAR",
    name: "Saudi Riyal",
    symbol: "﷼",
    decimal_digits: 2,
    countries: ["Saudi Arabia"],
  },
  {
    value: "SGD",
    name: "Singapore Dollar",
    symbol: "S$",
    decimal_digits: 2,
    countries: ["Singapore"],
  },
  {
    value: "ZAR",
    name: "South African Rand",
    symbol: "R",
    decimal_digits: 2,
    countries: ["South Africa"],
  },

  {
    value: "KRW",
    name: "South Korean Won",
    symbol: "₩",
    decimal_digits: 0,
    countries: ["South Korea"],
  },
  {
    value: "SEK",
    name: "Swedish Krona",
    symbol: "kr",
    decimal_digits: 2,
    countries: ["Sweden"],
  },
  {
    value: "CHF",
    name: "Swiss Franc",
    symbol: "CHF",
    decimal_digits: 2,
    countries: ["Switzerland", "Liechtenstein"],
  },

  {
    value: "THB",
    name: "Thai Baht",
    symbol: "฿",
    decimal_digits: 2,
    countries: ["Thailand"],
  },
  {
    value: "TRY",
    name: "Turkish Lira",
    symbol: "₺",
    decimal_digits: 2,
    countries: ["Turkey"],
  },
  {
    value: "USD",
    name: "US Dollar",
    symbol: "$",
    decimal_digits: 2,
    countries: ["United States", "Ecuador", "El Salvador"],
  },
  {
    value: "AED",
    name: "UAE Dirham",
    symbol: "د.إ",
    decimal_digits: 2,
    countries: ["United Arab Emirates"],
  },
];

export default Currencies;
