const Currencies = [
  {
    value: "AUD",
    name: "Australian Dollar",
    symbol: "A$",
    decimal_digits: 2,
    countries: ["Australia"],
    countryCode: "AU",
  },
  {
    value: "BRL",
    name: "Brazilian Real",
    symbol: "R$",
    decimal_digits: 2,
    countries: ["Brazil"],
    countryCode: "BR",
  },
  {
    value: "GBP",
    name: "British Pound",
    symbol: "£",
    decimal_digits: 2,
    countries: ["United Kingdom"],
    countryCode: "GB",
  },
  {
    value: "CAD",
    name: "Canadian Dollar",
    symbol: "C$",
    decimal_digits: 2,
    countries: ["Canada"],
    countryCode: "CA",
  },
  {
    value: "CNY",
    name: "Chinese Yuan",
    symbol: "¥",
    decimal_digits: 2,
    countries: ["China"],
    countryCode: "CN",
  },
  {
    value: "CZK",
    name: "Czech Koruna",
    symbol: "Kč",
    decimal_digits: 2,
    countries: ["Czech Republic"],
    countryCode: "CZ",
  },
  {
    value: "DKK",
    name: "Danish Krone",
    symbol: "kr",
    decimal_digits: 2,
    countries: ["Denmark"],
    countryCode: "DK",
  },
  {
    value: "EUR",
    name: "Euro",
    symbol: "€",
    decimal_digits: 2,
    countries: ["Germany", "France", "Italy", "Spain", "Netherlands"],
    countryCode: "EU",
  },
  {
    value: "HKD",
    name: "Hong Kong Dollar",
    symbol: "HK$",
    decimal_digits: 2,
    countries: ["Hong Kong"],
    countryCode: "HK",
  },
  {
    value: "INR",
    name: "Indian Rupee",
    symbol: "₹",
    decimal_digits: 2,
    countries: ["India"],
    countryCode: "IN",
  },
  {
    value: "IDR",
    name: "Indonesian Rupiah",
    symbol: "Rp",
    decimal_digits: 0,
    countries: ["Indonesia"],
    countryCode: "ID",
  },
  {
    value: "ILS",
    name: "Israeli Shekel",
    symbol: "₪",
    decimal_digits: 2,
    countries: ["Israel"],
    countryCode: "IL",
  },
  {
    value: "JPY",
    name: "Japanese Yen",
    symbol: "¥",
    decimal_digits: 0,
    countries: ["Japan"],
    countryCode: "JP",
  },
  {
    value: "MYR",
    name: "Malaysian Ringgit",
    symbol: "RM",
    decimal_digits: 2,
    countries: ["Malaysia"],
    countryCode: "MY",
  },
  {
    value: "MXN",
    name: "Mexican Peso",
    symbol: "$",
    decimal_digits: 2,
    countries: ["Mexico"],
    countryCode: "MX",
  },
  {
    value: "NZD",
    name: "New Zealand Dollar",
    symbol: "NZ$",
    decimal_digits: 2,
    countries: ["New Zealand"],
    countryCode: "NZ",
  },
  {
    value: "NOK",
    name: "Norwegian Krone",
    symbol: "kr",
    decimal_digits: 2,
    countries: ["Norway"],
    countryCode: "NO",
  },
  {
    value: "PHP",
    name: "Philippine Peso",
    symbol: "₱",
    decimal_digits: 2,
    countries: ["Philippines"],
    countryCode: "PH",
  },
  {
    value: "PLN",
    name: "Polish Zloty",
    symbol: "zł",
    decimal_digits: 2,
    countries: ["Poland"],
    countryCode: "PL",
  },
  {
    value: "RUB",
    name: "Russian Ruble",
    symbol: "₽",
    decimal_digits: 2,
    countries: ["Russia"],
    countryCode: "RU",
  },
  {
    value: "SAR",
    name: "Saudi Riyal",
    symbol: "﷼",
    decimal_digits: 2,
    countries: ["Saudi Arabia"],
    countryCode: "SA",
  },
  {
    value: "SGD",
    name: "Singapore Dollar",
    symbol: "S$",
    decimal_digits: 2,
    countries: ["Singapore"],
    countryCode: "SG",
  },
  {
    value: "ZAR",
    name: "South African Rand",
    symbol: "R",
    decimal_digits: 2,
    countries: ["South Africa"],
    countryCode: "ZA",
  },
  {
    value: "KRW",
    name: "South Korean Won",
    symbol: "₩",
    decimal_digits: 0,
    countries: ["South Korea"],
    countryCode: "KR",
  },
  {
    value: "SEK",
    name: "Swedish Krona",
    symbol: "kr",
    decimal_digits: 2,
    countries: ["Sweden"],
    countryCode: "SE",
  },
  {
    value: "CHF",
    name: "Swiss Franc",
    symbol: "CHF",
    decimal_digits: 2,
    countries: ["Switzerland", "Liechtenstein"],
    countryCode: "CH",
  },
  {
    value: "THB",
    name: "Thai Baht",
    symbol: "฿",
    decimal_digits: 2,
    countries: ["Thailand"],
    countryCode: "TH",
  },
  {
    value: "TRY",
    name: "Turkish Lira",
    symbol: "₺",
    decimal_digits: 2,
    countries: ["Turkey"],
    countryCode: "TR",
  },
  {
    value: "USD",
    name: "US Dollar",
    symbol: "$",
    decimal_digits: 2,
    countries: ["United States", "Ecuador", "El Salvador"],
    countryCode: "US",
  },
  {
    value: "AED",
    name: "UAE Dirham",
    symbol: "د.إ",
    decimal_digits: 2,
    countries: ["United Arab Emirates"],
    countryCode: "AE",
  },
];

export default Currencies;
